---
- hosts: all
  become: True
  tasks:
  - debug: 
      msg: "the value of buildno= {{ build }}"
  
  tasks:
  - name: Docker login to nexus
    docker_login:
      registry: 34.73.184.207:8083
      username: "{{ user }}"
      password: "{{ password }}"

  - name: Pull an image from nexus
    docker_image:
      name: "34.73.184.207:8083/devops/employee-microservice-nodenpminstall:{{ build }}"

  - name: Run the image as container
    docker_container:
      name: employee-microservice-nodenpminstall
      image: "34.73.184.207:8083/devops/employee-microservice-nodenpminstall:{{ build }}"
      state: started
      ports: 8000:8000
